### ISSUE TITLE
Unable to install "PixelFreeEffects"

### ISSUE THREAD

**Issue by fangwei520** [mu-code007/PixelFreeEffects#1]
Unable to install "PixelFreeEffects"

**Comment by iossun** [comment]
3q ,我调试下线上

**Comment by iossun** [comment]
git 提交大小写不明感，导致换过库名后，没有提交上 

本地代码确认 PixelFree.framework -》PixelFree ，十分抱歉

**Comment by fangwei520** [comment]
> git 提交大小写不明感，导致换过库名后，没有提交上
> 
> 本地代码确认 PixelFree.framework -》PixelFree ，十分抱歉

感谢解决，现在能跑起来了，但是只有美白和滤镜生效，别的都没生效，是要去face++替换sdk的api_key api_secret吗

**Comment by sculg** [comment]
除了face++人脸识别方案，还有什么开源可用的人脸识别方案吗？

**Comment by iossun** [comment]
TNN

发自我的iPhone

**Comment by iossun** [comment]
新版本的用的开源人脸


发自我的iPhone

**Comment by DaiJunMaster** [comment]
> 

请问作者大大新版本在哪里可以下载哇，找了一圈没有看到🙏
