### ISSUE TITLE
Xcode14.0.1编译时会报错

### ISSUE THREAD

**Issue by daiyangyang945** [mu-code007/PixelFreeEffects#11]
<img width="553" alt="截屏2022-12-27 17 53 14" src="https://user-images.githubusercontent.com/26043410/209648584-e729131f-d133-4d32-b188-2005416fc97c.png">

**Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions**

**Comment by mu-code007** [comment]
貌似只是 warning,后面我尝试修复

**Comment by daiyangyang945** [comment]
还发现了一个问题，我在你的项目上present或push一个新的PFVideoController后，再返回原controller后无法点击了，甚至连摄像头的画面都卡住了。
为了以防万一我自己新建了一个项目测试一下，结果也是一样的，在present或push一个新的PFVideoController后再返回原Controller就卡住了。


然后把该段代码`self.mPixelFree = [[SMPixelFree alloc] initWithProcessContext:nil srcFilterPath:face_FiltePath srcDetectPath:face_DetectPath authFile:authFile];`注释就又正常了，所以可能问题是出在framework里

**Comment by mu-code007** [comment]
SMPixelFree 内存中不能同时是存在多个对象，构建成本比较大，可以尝试写成单例。
