### ISSUE TITLE
效果很棒！

### ISSUE THREAD

**Issue by rootkit** [mu-code007/PixelFreeEffects#12]
这是github最牛的项目啦，好像android 不支持图片美颜？

**Comment by rootkit** [comment]
用下面的方法来支持图片美颜，没有错误，但是图片没有美颜效果，问题出在哪里呢？
       
       {
        mPixelFree.create()

        val face_fiter = mPixelFree.readBundleFile(this, "face_fiter.bundle")
        mPixelFree.createBeautyItemFormBundle(
            face_fiter,
            face_fiter.size,
            PFSrcType.PFSrcTypeFilter
        )

        bitmap = drawableToBitamp(getDrawable(R.drawable.qingniangan));
        
        val bytesArray = bitmapToRgba(bitmap!!)
        OpenGLTools.load()

        rgbaProducer.mWidth = bitmap?.width ?: 0
        rgbaProducer.mHeight = bitmap?.height ?: 0
        rgbaProducer.rgbaByteArray = bytesArray

        val frame = VideoFrame(
            rgbaProducer.mWidth,
            rgbaProducer.mHeight,
            ImgFmt.IMAGE_FORMAT_RGBA,
            rgbaProducer.rgbaByteArray!!,
            rgbaProducer.pixelStride,
            rgbaProducer.rowPadding
        )


        mPixelFree.processWithBuffer(frame.toPFIamgeInput())
        }
        
            public static byte[] bitmapToRgba(Bitmap bitmap) {
        if (bitmap.getConfig() != Bitmap.Config.ARGB_8888)
            throw new IllegalArgumentException("Bitmap must be in ARGB_8888 format");
        int[] pixels = new int[bitmap.getWidth() * bitmap.getHeight()];
        byte[] bytes = new byte[pixels.length * 4];
        bitmap.getPixels(pixels, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
        int i = 0;
        for (int pixel : pixels) {
            // Get components assuming is ARGB
            int A = (pixel >> 24) & 0xff;
            int R = (pixel >> 16) & 0xff;
            int G = (pixel >> 8) & 0xff;
            int B = pixel & 0xff;
            bytes[i++] = (byte) R;
            bytes[i++] = (byte) G;
            bytes[i++] = (byte) B;
            bytes[i++] = (byte) A;
        }
        return bytes;
    }

**Comment by mu-code007** [comment]
1月29，andriod 图片美颜暂不支持，需要改下接口

**Comment by rootkit** [comment]
重新修改了代码，把它当作一帧视频，放入processWithBuffer

1.  val bytesArray = RGBAByte.bitmapToRgba(bitmap!!)                       // 把bitmap 转 RGBA bytesArray

2.     rgbaProducer.mWidth = bitmap?.width ?: 0                                   // 放入 VideoFrame
        rgbaProducer.mHeight = bitmap?.height ?: 0
        rgbaProducer.rgbaByteArray = bytesArray
        
          val frame = VideoFrame(
            rgbaProducer.mWidth,
            rgbaProducer.mHeight,
            ImgFmt.IMAGE_FORMAT_RGBA,
            rgbaProducer.rgbaByteArray!!,
            rgbaProducer.pixelStride,
            rgbaProducer.rowPadding
        )
        
 3. mPixelFree.processWithBuffer(frame.toPFIamgeInput())                 //放入processWithBuffer进行处理
 
 4. mPixelFree.pixelFreeSetBeautyFiterParam(                                        //设置美颜参数
            PFBeautyFiterType.PFBeautyFiterTypeFaceWhitenStrength,
            1.0f
        )
5.   val byteBuffer1 = ByteBuffer.wrap(ByteArray(frame.data.size))     //glReadPixels 取出数据
        GLES30.glReadPixels(0, 0, frame.width, frame.height,
            GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, byteBuffer1);
        val stitchBmp = Bitmap.createBitmap(frame.width, frame.height, Bitmap.Config.ARGB_8888)
        
  运行效果：
  比原图片饱和度要高
  美颜效果不明显，问题出在哪里呢？

**Comment by rootkit** [comment]
重新修改了代码，把它当作一帧视频，放入processWithBuffer

val bytesArray = RGBAByte.bitmapToRgba(bitmap!!)                   //  1. 把bitmap 转 RGBA bytesArray

rgbaProducer.mWidth = bitmap?.width ?: 0                                   //  2. 放入 VideoFrame
 rgbaProducer.mHeight = bitmap?.height ?: 0
 rgbaProducer.rgbaByteArray = bytesArray
 
   val frame = VideoFrame(
     rgbaProducer.mWidth,
     rgbaProducer.mHeight,
     ImgFmt.IMAGE_FORMAT_RGBA,
     rgbaProducer.rgbaByteArray!!,
     rgbaProducer.pixelStride,
     rgbaProducer.rowPadding
 )
 
 OpenGLTools.load()                                                                         // 3.绑定纹理
 
mPixelFree.processWithBuffer(frame.toPFIamgeInput())             // 4. 放入processWithBuffer进行处理

mPixelFree.pixelFreeSetBeautyFiterParam(                                  // 5. 设置美颜参数
PFBeautyFiterType.PFBeautyFiterTypeFaceWhitenStrength,
1.0f
)

val byteBuffer1 = ByteBuffer.wrap(ByteArray(frame.data.size)) // 6. glReadPixels 取出数据
GLES30.glReadPixels(0, 0, frame.width, frame.height,
GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, byteBuffer1);
val stitchBmp = Bitmap.createBitmap(frame.width, frame.height, Bitmap.Config.ARGB_8888)

运行效果：
比原图片饱和度要高
美颜效果不明显，问题出在哪里呢？

**Comment by mu-code007** [comment]
视频接口，内部未实现 RGBA 转 textureID。
如果要尝试，你可以试下 PFIamgeInput 中带上 bitmap 和 textureID，bitmap 用于人脸点位算法，textureID 用于效果渲染。

**Comment by rootkit** [comment]
按照大神的步骤，尝试了一下：
1. mPixelFree.create()

2. val face_fiter = mPixelFree.readBundleFile(this, "face_fiter.bundle")
        mPixelFree.createBeautyItemFormBundle(
            face_fiter,
            face_fiter.size,
            PFSrcType.PFSrcTypeFilter
        )
        
 3. val bytesArray = RGBAByte.bitmapToRgba(bitmap!!)
 
 4. OpenGLTools.load()
 
 5. OpenGLTools.createTexture(
            bitmap!!.width,
            bitmap!!.height,
            ByteBuffer.wrap(bytesArray, 0,bytesArray.size)
        )
  6.    val pxInput = PFIamgeInput().apply {
            textureID = OpenGLTools.textures!![0]
            wigth = bitmap!!.width
            height = bitmap!!.height
            p_BGRA = bytesArray
            p_Y = null
            p_CbCr = null
            stride_BGRA = 0
            stride_Y = 0
            stride_CbCr = 0
            format = PFDetectFormat.PFFORMAT_IMAGE_RGBA
            rotationMode = PFRotationMode.PFRotationMode90
        }
        
  7. mPixelFree.processWithBuffer(pxInput)
  
  8. mPixelFree.pixelFreeSetBeautyFiterParam(
            PFBeautyFiterType.PFBeautyFiterTypeFaceWhitenStrength,
            1.0f
        )
     
  9.  val byteBuffer1 = ByteBuffer.wrap(ByteArray(bytesArray.size))
        GLES30.glReadPixels(0, 0, bitmap!!.width, bitmap!!.height,
            GLES30.GL_RGBA, GLES30.GL_UNSIGNED_BYTE, byteBuffer1);
        val stitchBmp = Bitmap.createBitmap(bitmap!!.width, bitmap!!.width, Bitmap.Config.ARGB_8888)
        stitchBmp.copyPixelsFromBuffer(byteBuffer1)
       
    运行效果：
    全程无错运行，一直跑到jni层后出来，然后拿buffer数据, 效果没有出来
    可能是我哪个地方的时序弄错了吧？

**Comment by rootkit** [comment]
是不是 p_BGRA = bytesArray 这个bytesArray是RGBA的，是不是要转换成BGRA?

**Comment by rootkit** [comment]
效果出来啦
需要执行mPixelFree.processWithBuffer(pxInput) 2次以上
因此也发现代码有点小瑕疵，代码处理时最好提前取一帧数据，这样就同步啦

**Comment by mu-code007** [comment]
不错不错
