### ISSUE TITLE
关于TNN的问题

### ISSUE THREAD

**Issue by DelogoTeam** [mu-code007/PixelFreeEffects#13]
大神你好，我最近在做iOS人脸识别相关的功能，使用了开源的TNN，然后我在打包framework的时候遇到了问题。
我将TNN的framework、bundle、model打包进了我的framework，build成功了，但是在我引入打包好的framework时却无法编译成功。
我在您的issue下发现了您的项目也使用了TNN的人脸识别，而且成功打包进了您的framework中，所以我冒昧来询问一下您是如何打包成功的。万分期待您的回复

**Comment by mu-code007** [comment]
TNN 打成静态库，让后 link 到你的 framework

**Comment by DelogoTeam** [comment]
非常感谢您的提醒
