### ISSUE TITLE
运行demo调节没效果

### ISSUE THREAD

**Issue by heyehao2008** [mu-code007/PixelFreeEffects#15]
控制台打印Certificate required....
相机进入，只有默认的美颜配置，调节各种参数没效果，滤镜也没有效果
是使用了什么认证过期了吗？

**Comment by mu-code007** [comment]
嗯，过期了，demo 更新了授权

**Comment by heyehao2008** [comment]
嗯，可以了。
请问一下如果我在自己的项目中使用你的SDK，需要付费还是什么？要获取你那个授权？

**Comment by mu-code007** [comment]
需要授权的

**Comment by mu-code007** [comment]
有购买美颜计划吗？发自我的 iPhone在 2023年5月29日，11:18，天府城主 ***@***.***> 写道：﻿
嗯，可以了。
请问一下如果我在自己的项目中使用你的SDK，需要付费还是什么？要获取你那个授权？
